[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = ["cd backend && yarn install --ignore-engines"]

[phases.build]
cmds = ["cd backend && yarn build"]

[start]
cmd = "cd backend && ./start.sh"
