import LoadingIcon from "@/assets/Icons/LoadingIcon";
import FormManager from "@/Components/Page/Common/FormManager";
import DataTable from "@/Components/UI/DataTable";
import Dropdown from "@/Components/UI/Dropdown";
import PopupModal from "@/Components/UI/PopupModal";
import TextBox from "@/Components/UI/TextBox";
import { getCurrencySymbol, countDecimals } from "@/helpers";
import {
  WALLET_FETCH,
  WALLET_FUND_CREATE,
  WalletAction,
} from "@/Redux/Actions/WalletAction";
import { IWallet, pageProps, rootReducer } from "@/utils/types";
import { Search } from "@mui/icons-material";
import {
  Box,
  Button,
  Divider,
  InputAdornment,
  Typography,
  useTheme,
} from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import * as yup from "yup";

const columns = ["#", "Company Name", "Email", "Amount"];

const fundInitial = {
  amount: "",
  currency: "USD",
};

const Wallet = ({ setPageName }: pageProps) => {
  const theme = useTheme();
  const dispatch = useDispatch();
  const router = useRouter();
  const walletState = useSelector((state: rootReducer) => state.walletReducer);
  const [fiatData, setFiatData] = useState<IWallet[]>([]);
  const [cryptoData, setCryptoData] = useState<IWallet[]>([]);
  const [searchValue, setSearchValue] = useState("");
  const [loading, setLoading] = useState(true);
  const [totalBalance, setTotalBalance] = useState(0);
  const [open, setOpen] = useState(false);

  const fundSchema = yup.object().shape({
    amount: yup.string().required("amount is required!"),
  });

  useEffect(() => {
    setPageName("Wallets");
    dispatch(WalletAction(WALLET_FETCH));
  }, []);

  useEffect(() => {
    if (walletState.walletList.length > 0) {
      let total = 0;
      for (let i = 0; i < walletState.walletList.length; i++) {
        const currentWallet = walletState.walletList[i];
        total += Number(currentWallet.amount_in_usd);
      }
      const tempFiat = walletState.walletList.filter(
        (x) => x.currency_type === "FIAT"
      );
      const tempCrypto = walletState.walletList.filter(
        (x) => x.currency_type === "CRYPTO"
      );
      setTotalBalance(total);
      setCryptoData(tempCrypto);
      setFiatData(tempFiat);
      setLoading(false);
    }
  }, [walletState.walletList]);

  useEffect(() => {
    if (walletState.amount !== 0) {
      router.push("/payment");
    }
  }, [walletState.amount]);

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchValue(e.target.value);
  };

  const handleSubmit = (values: any) => {
    dispatch({ type: WALLET_FUND_CREATE, payload: { ...values } });
  };

  return (
    <>
      <Head>
        <title>BozzWallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PopupModal
        open={open}
        showClose
        handleClose={() => setOpen(false)}
        headerText={"Add Funds"}
      >
        <Box sx={{ minWidth: "450px" }}>
          <FormManager
            initialValues={fundInitial}
            yupSchema={fundSchema}
            onSubmit={handleSubmit}
          >
            {({
              errors,
              handleBlur,
              handleChange,
              submitDisable,
              touched,
              values,
            }) => (
              <>
                <TextBox
                  name="amount"
                  placeholder="Enter amount"
                  label="Amount"
                  value={values.amount}
                  type="number"
                  fullWidth
                  onChange={handleChange}
                  onBlur={handleBlur}
                  error={touched.amount && errors.amount}
                  helperText={touched.amount && errors.amount && errors.amount}
                />
                <Box sx={{ width: "100%", mt: 3 }}>
                  <Dropdown
                    name="currency"
                    placeholder="Enter currency"
                    label="Currency"
                    value={values.currency}
                    type="number"
                    fullWidth
                    menuItems={[
                      { label: "USD", value: "USD" },
                      { label: "NGN", value: "NGN" },
                    ]}
                    getValue={(value: any) => {
                      const e: any = {
                        target: {
                          name: "currency",
                          value,
                        },
                      };
                      handleChange(e);
                    }}
                    onBlur={handleBlur}
                    error={touched.currency && errors.currency}
                    helperText={
                      touched.currency && errors.currency && errors.currency
                    }
                  />
                </Box>
                <Box sx={{ mt: 5, mb: 3, display: "flex" }}>
                  <Button
                    variant="rounded"
                    disabled={walletState.loading ?? submitDisable}
                    type="submit"
                  >
                    Add
                  </Button>
                </Box>
              </>
            )}
          </FormManager>
        </Box>
      </PopupModal>
      <Box sx={{ m: 2, mb: 5 }}>
        {loading ? (
          <>
            <Box
              sx={{
                height: "375px",
                width: "100%",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <LoadingIcon size={75} />
            </Box>
          </>
        ) : (
          <>
            <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
              <Typography sx={{ fontSize: 18, fontWeight: 900 }}>
                Total Wallet Balance:{" "}
              </Typography>
              <Typography
                sx={{ fontSize: 18, fontWeight: 900, color: "text.secondary" }}
              >
                $ {totalBalance.toFixed(2)}
              </Typography>
            </Box>
            <Box
              sx={{
                mt: 2,
                display: "flex",
                alignItems: "flex-end",
                justifyContent: "space-between",
              }}
            >
              <Typography sx={{ fontWeight: 700 }}>Fiat Wallets</Typography>
              <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
                <Button
                  variant="rounded"
                  color="secondary"
                  onClick={() => router.push("/withdraw")}
                >
                  Withdraw
                </Button>
                <Button
                  variant="rounded"
                  color="primary"
                  onClick={() => {
                    setOpen(true);
                  }}
                >
                  Add Funds
                </Button>
              </Box>
            </Box>
            <Divider sx={{ my: 2 }} />
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 3,
                flexWrap: "wrap",
              }}
            >
              {fiatData.map((x) => (
                <Box
                  key={x.id}
                  sx={{
                    border: "1px solid",
                    width: "250px",
                    height: "100%",
                    borderRadius: "10px",
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "space-between",
                    p: 3,
                  }}
                >
                  <Typography sx={{ fontSize: "24px", fontWeight: 700 }}>
                    {x.wallet_type}
                  </Typography>
                  <Typography
                    sx={{
                      fontSize: 30,
                      fontWeight: 900,
                      textAlign: "right",
                      color: "text.secondary",
                    }}
                  >
                    {getCurrencySymbol(x.wallet_type, x.amount.toFixed(2))}
                  </Typography>
                  <Typography
                    sx={{
                      fontSize: 12,
                      fontWeight: 700,
                      textAlign: "right",
                      color: theme.palette.error.main,
                    }}
                  >
                    ({getCurrencySymbol("USD", x.amount_in_usd)})
                  </Typography>
                </Box>
              ))}
            </Box>
            <Typography sx={{ fontWeight: 700, mt: 5 }}>
              Crypto Wallets
            </Typography>
            <Divider sx={{ my: 2 }} />
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 3,
                flexWrap: "wrap",
              }}
            >
              {cryptoData.map((x) => (
                <Box
                  key={x.id}
                  sx={{
                    border: "1px solid",
                    width: "250px",
                    height: "100%",
                    borderRadius: "10px",
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "space-between",
                    p: 3,
                  }}
                >
                  <Typography sx={{ fontSize: "24px", fontWeight: 700 }}>
                    {x.wallet_type}
                  </Typography>
                  <Typography
                    sx={{
                      fontSize: 30,
                      fontWeight: 900,
                      textAlign: "right",
                      color: "text.secondary",
                    }}
                  >
                    {getCurrencySymbol(
                      x.wallet_type,
                      countDecimals(x.amount) > 8
                        ? x.amount.toFixed(8)
                        : x.amount
                    )}
                  </Typography>
                  <Typography
                    sx={{
                      fontSize: 12,
                      fontWeight: 700,
                      textAlign: "right",
                      color: theme.palette.error.main,
                    }}
                  >
                    ({getCurrencySymbol("USD", x.amount_in_usd)})
                  </Typography>
                  <Typography
                    sx={{
                      fontSize: 12,
                      fontWeight: 700,
                      textAlign: "left",
                      color: theme.palette.grey[500],
                      overflow: "hidden",
                      textOverflow: "ellipsis",
                      whiteSpace: "nowrap",
                      maxWidth: "100%",
                    }}
                    title={x?.wallet_address ?? ""}
                  >
                    {x?.wallet_address ?? ""}
                  </Typography>
                </Box>
              ))}
            </Box>
          </>
        )}
      </Box>
    </>
  );
};

export default Wallet;
